[package]
name = "escape"
version = "0.1.31"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Run arbitrary commands via http"
repository = "https://github.com/sigmaSd/escape"
license = "MIT"

[dependencies]